// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvwscxburlixyqkbhfux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52d3NjeGJ1cmxpeHlxa2JoZnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Mjk1MTEsImV4cCI6MjA2NjEwNTUxMX0.ppBJapu82yVC7wBeXqZlkgceMGLpPt9VA58AOSmUlhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);